### ISSUE TITLE
MediaStreamSource

### ISSUE THREAD

**Issue by mcosmin222** [Alovchin91/flac-winrt#4]
I managed to get a media stream source ready. It supports play & pause now and if you give me a couple more hours/days/weeks/months/years I will get seeking working too.

Basically, what you need to get play&pause working is to modify the MediaStreamSource_starting event and call args.request.SetActualStartPosition to some value which is different than a 0/0/0/0 timespan. This can be easily done by setting said timespan to the playback position of the last played sample before the pause.

You also need to detect if the starting event was called because of resume after pause, or after seeking.

**Comment by mcosmin222** [comment]
Apparently, the quad core windows phones support 24 bit audio.
FLac goes out of memory in a few minutes xD

**Comment by Alovchin91** [comment]
@mcosmin222 Hmm, as far as I know FLAC doesn't support 24 bit audio.

**Comment by mcosmin222** [comment]
Ok so I found out the trickery to have buffer time AND be able to respond to pauses and resume properly. In the paused even, you have to set the buffer time to zero. Then in the starting event restore it whatever value you want it to have. Genius isn't it? we should have thought of this earlier. I think the buffer time helps you implement gapless playback.
