### ISSUE TITLE
Как воспроизвести flac 24 бита?

### ISSUE THREAD

**Issue by wshadw** [Alovchin91/flac-winrt#9]
Привет, я использую flac-winrt в своём приложении для wp8.1 runtime и у меня есть проблема с воспроизведением 24 битного флака. При воспроизведении он просто шумит.
Я попробовал увеличить размер буфера в 100 раз, он запел, но не долго. На слух, заполняется только треть буфера, остальное время просто шипение.

Как можно исправить данную проблему?
Спасибо.

**Comment by Alovchin91** [comment]
@wshadw По идее это должно зависеть от формата вывода. В примере это данная строка:

``` cs
var encodingProperties = AudioEncodingProperties.CreatePcm(
    streamInfo.SampleRate, streamInfo.ChannelCount, streamInfo.BitsPerSample);
```

**Comment by wshadw** [comment]
@Alovchin91 Ну параметры flac там правильно определяются.

**Comment by Alovchin91** [comment]
@wshadw В таком случае ошибка может быть в алгоритме вычисления размера буфера MediaSample. Если возможно, предоставьте, пожалуйста, код и файл, который Вы пытаетесь воспроизвести.

**Comment by ChipsetSV** [comment]
Проблема там такая, действительно, была. Не знаю, как на последний момент. Она решаема, гляну сейчас как решилось..

**Comment by ChipsetSV** [comment]
Да, нужен пример кода, который сейчас работает у вас. С ходу не могу вспомнить, какие именно изменения были внесены. Но факт, что проблема решаема, по-моему, изменением способа чтения семплов.

**Comment by wshadw** [comment]
Дабы исключить ошибку своего проекта сейчас я всё тестирую на этом примере github.com/Alovchin91/flac-winrt/tree/master/examples

**Comment by Alovchin91** [comment]
@wshadw Мне в любом случае понадобится Ваш FLAC-файл, чтобы в этой проблеме разобраться.

**Comment by ChipsetSV** [comment]
Я использую такой код сейчас, последние нововведения - колбэки - пока не использую:

```
bool StreamDecoder::ProcessSingle()
            {
                FLAC__ASSERT(IsValid);
                return !!(::FLAC__stream_decoder_process_single(decoder_));
            }
```

```
IBuffer buffer = this._mediaDecoder.SingleSample();
                    _sampleCount++;
                    if (buffer.Length > 0)
                    {
                        GC.AddMemoryPressure(buffer.Length);
                        sample = MediaStreamSample.CreateFromBuffer(buffer, TimeSpan.FromSeconds(this._currentTime));
                        var duration = this._mediaDecoder.GetDurationFromBufferSize(buffer.Length);
                        sample.Duration = TimeSpan.FromSeconds(duration);
                        this._currentTime += duration;
                    }
                    else
                    {
                        this._currentTime = 0.0;
                        this._mediaDecoder.Seek(0);
                    }
```

SingleSample просто вызывает ProcessSingle.

**Comment by ChipsetSV** [comment]
@Alovchin91 можно использовать любой 24битный флак.
Кстати, не планируется реализация ALAC?

**Comment by Alovchin91** [comment]
@ChipsetSV Я над этим думал, в принципе хотелось бы сделать. Осталось время найти )

**Comment by ChipsetSV** [comment]
@Alovchin91 Время - самое главное ) ALAC - было бы шик, желающих его использовать хватает )
Были тоже мысли сделать, но не хватает того самого, времени )

**Comment by Alovchin91** [comment]
@ChipsetSV Попробую, но давать прогнозы не готов. ALAC использует контейнеры, поэтому с ним немного сложнее. Предоставлять декодер ALAC без демуксера контейнеров было бы неправильно. Поэтому пока что потихоньку обновляю другие кодеки (Opus и Ogg Vorbis). Если критично, можно попробовать FFmpeg.

**Comment by ChipsetSV** [comment]
@Alovchin91 Почему-то в жизни ни разу с опусом не сталкивался ) Контейнеры.. ну тут ничего не скажу, конечно, потому что уже не помню, чего там за потроха. Но готового решения на плюсах найти с ходу не удалось, чтобы потом можно было быстро использовать в шарпах.
Огг успешно люди слушают, как, собственно, и флак (во флаке только иногда остались щелчки при начале воспроизведения или при seek'е) ) Ты вообще молодец )

**Comment by wshadw** [comment]
@ChipsetSV чёт у меня не вышло сделать изменения по вашему куску кода. Там есть изменение _sampleCount, у меня вообще нету такого поля.
"SingleSample просто вызывает ProcessSingle." но SingleSample должен вернуть IBuffer, а ProcessSingle возвращает bool.

**Comment by Alovchin91** [comment]
@ChipsetSV Щелчки во флаке - это, возможно, куски метаданных попадают в аудиопоток, либо, если ещё и при seek, может некорректно задаваться время начала аудиопотока в обработчике `MediaStreamSource.Starting` (`e.Request.SetActualStartPosition(TimeSpan.FromSeconds(this._currentTime));` в примере).
Касаемо контейнеров ALAC - насколько я понял, там либо MP4, либо CAF. Для MP4 можно использовать библиотеку mp4v2, для CAF пока не искал.

@wshadw Посмотрю завтра, что можно сделать по поводу 24-битного FLAC.

**Comment by wshadw** [comment]
по поводу щелчков, это скорее косяк винды и аудиодрайвера, тк иногда чёт ломается и есть щелчки при переключении треков или перемотке даже с выключенным звуком в любом плеере включая стандартный, до перезагрузки.
@Alovchin91 Спасибо, жду)

**Comment by ChipsetSV** [comment]
@wshadw Вот в стандартном не слышал щелчков, потому что им не пользовался ) А вообще да, это вряд ли проблема кодека, потому что щелкает даже с выключенным звуком.
@Alovchin91 За библиотеку mp4v2 спасибо, надо будет посмотреть, не наталкивался на нее чего-то. А CAF - вообще редкий формат, по-моему, не стоит и внимания сейчас.

По поводу 24 бит. Мне помогло как раз избавление от IBuffer, то есть результат ProcessSingle библиотеки сразу подавал на воспроизведение, тогда проблем со звуком нет. Формирование буфера пробовал менять, но к успеху не пришел, наверно, нужно менять принцип его заполнения.

**Comment by wshadw** [comment]
@ChipsetSV я стандартным тоже не пользуюсь, просто когда щелчки услышал ради теста запустил и проверил)

Вы меня ещё больше запутали). Вы пишите про избавление от IBuffer, но в приведеном куске кода он у вас есть и именно его SingleSample и возвращает
IBuffer buffer = this._mediaDecoder.SingleSample();
да и метод MediaStreamSample.CreateFromBuffer принимает именно IBuffer и не имеет других перегрузок.

Видимо вы его с чем то другим спутали, либо я вас не так понял.

**Comment by ChipsetSV** [comment]
@wshadw Действительно, тут я чего-то совсем попутал ) Сложные выходные )
Да, буфер там используется, но алгоритм его заполнения простой:
В WriteCallback
`_currentBuffer = e.GetBuffer();`
То есть у декодера запрашиваем ProcessSingle, а он свою очередь, вызывает WriteCallback, где мы и забираем текущие данные и передаем винде на воспроизведение.
Но это не самый эффективный способ, так как возникает проблема, что быстро забивается память ) Тут еще можно покумекать по оптимизации.

**Comment by wshadw** [comment]
@ChipsetSV 
таки запело) в итоге добавил поле  _currentBuffer, и метод SingleSample() стал его возвращать, получилось так

```
    public IBuffer SingleSample()
    {
        this.EnsureMetadataRead();
        bool result = this._streamDecoder.ProcessSingle();
        if (!result)
            this._currentData = _noCurrentData;
        return _currentBuffer;
    }
    private void WriteCallback(object sender, StreamDecoderWriteEventArgs e)
    {
        IBuffer currentSample = e.GetBuffer();
        _currentBuffer = currentSample;//добавленная строка
        GC.AddMemoryPressure(currentSample.Capacity);
        this._currentData = new BufferSegment(currentSample);
        e.SetResult(StreamDecoderWriteStatus.Continue);
    }
```

по поводу памяти не знаю, я сделал не напрямую  e.GetBuffer() а взял currentSample, у которого дальше вон есть строчка от перегруза памяти.

**Comment by wshadw** [comment]
@ChipsetSV появились щелчки при перемотке, и именно у 24 битного флака, у 16 и у мп3 всё ок.
А вообще спасибо)

Спустя небольшое время после воспроизведения фоновый плеер вылетал, добавил перед _currentBuffer = currentSample; обнуление и запуск сборщика мусора и всё стало ок

**Comment by wshadw** [comment]
Спустя небольшое время после воспроизведения фоновый плеер вылетал, добавил перед _currentBuffer = currentSample; обнуление и запуск сборщика мусора и всё стало ок

**Comment by ChipsetSV** [comment]
@wshadw отлично, что все получилось )
А про вылеты - вот об этом я и говорил. Да, сбор мусора помогает, но это все-таки некрасивое решение.

**Comment by wshadw** [comment]
@ChipsetSV ну то что некрасиво с этим полностью согласен, но пока пойдёт, но вот незадача, случайно заметил что петь не перестаёт по окончании трека, а продолжает воспроизводить тишину

**Comment by ChipsetSV** [comment]
@wshadw вариант вполне рабочий, люди пользуются уже порядочное время, жалоб по этому поводу нет )
А вот воспроизведение тишины - такого не наблюдал.
Может быть, это связано с вычислением текущей позиции трека или даже не знаю.

**Comment by wshadw** [comment]
@ChipsetSV да уже решил проблему, вынес очистку буфера в другой метод который стал вызывать перед var buffer = this._mediaDecoder.SingleSample(); и стало норм, а то он чистился в методе WriteCallback, который переставал вызываться после завершения трека, но буфер был не пустой и он на нем циклился, а теперь всё норм)

**Comment by Alovchin91** [comment]
@ChipsetSV Я думаю тебе помогло избавление от BufferSegment. Уже и не помню, откуда его взял, но суть его была именно в том, чтобы не дать медиасистеме захлебнуться огромными буферами (не пойми меня правильно), а подавать сэмплы небольшими порциями.

@wshadw Рад, что всё решили без меня ) Проблема, видимо, в том, что в какой-то момент `bool result = this._streamDecoder.ProcessSingle();` возвращает `false`, и буфер сбрасывается. Надо будет посмотреть, почему там возвращается `false`.
Что же до оптимизации, то я делал так: в MediaSourceAdapter создавал пул IBuffer'ов (если не ошибаюсь, трёх буферов по 4000 байт вполне хватало на 16-битные файлы), и переиспользовал их вместо того, чтобы создавать новые. Я думаю, это решение вполне применимо вместо текущего (сейчас количество буферов динамическое, они становятся в очередь по мере обработки, и их общее число может достигать сотен).
